
package lms;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.EtchedBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class student extends javax.swing.JFrame {

    private JPanel jp1,jp2,jp3,jp4;
    private Connection conn;
    int id;
    JLabel jLabel2 ;
    JLabel jLabel1 ;
    JLabel jLabel3 ;
    JLabel jLabel4 ;
    JLabel jLabel5 ;
    JLabel jLabel6 ;
    JLabel jLabel7 ;
    JLabel startDate;
    JLabel endDate;
    JLabel leaveStatusLabel;
    JLabel leaveStatus;
    JTextField startDateTextField = new JTextField();

    JTextField endDateTextField = new JTextField();

    /**
     * Creates new form student
     */
    public student(Connection conn,int id) {
        this.id = id;
        this.conn = conn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {


        JMenuBar jMenuBar1 = new JMenuBar();
        JMenu jMenu1 = new JMenu();
        JMenu jMenu2 = new JMenu();
        JMenu jMenu3 = new JMenu();
        JMenuItem jMenuItem1 = new JMenuItem();
        JMenuItem jMenuItem2 = new JMenuItem();
        JMenu jMenu6 = new JMenu();
        jp1 = new JPanel();
        jp2 = new JPanel();
        jp3 = new JPanel();
        jp4 = new JPanel();
        JButton b1 = new JButton();

        jLabel2 = new JLabel();
        jLabel1 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel7 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        startDate = new JLabel();
        endDate = new JLabel();
        leaveStatusLabel = new JLabel();
        leaveStatus = new JLabel();



        startDateTextField.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
        endDateTextField.setFont(new Font("Roboto Mono", Font.PLAIN, 24));

        JButton applyButton = new JButton("Apply Now");
        applyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                applyButtonClicked(actionEvent);
            }


        });
        applyButton.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
        applyButton.setBackground(Color.DARK_GRAY);
        applyButton.setForeground(Color.WHITE);
        applyButton.setMargin(new Insets(10,25,10,25));
        setVisible(true);

        jMenu1.setText("Profile");
        jMenu1.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
        jMenuBar1.add(jMenu1);
        jMenu1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

//        jMenu2.setText("Profile");
//        jMenuBar1.add(jMenu2);
//        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jMenu2MouseClicked(evt);
//            }
//        });

        jMenu3.setText("Leave");
        jMenu3.setFont(new Font("Roboto Mono", Font.PLAIN, 24));

        jMenuItem1.setText("Apply");
        jMenuItem1.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
        jMenu3.add(jMenuItem1);
        jMenuItem1.addActionListener(this::leaveApplyClicked);
//        jMenuItem1.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent actionEvent) {
//
//            }
//        });

        jMenu1.setForeground(Color.WHITE);
        jMenu1.insertSeparator(100);
        jMenu2.setForeground(Color.WHITE);
        jMenu3.setForeground(Color.WHITE);
        jMenu6.setForeground(Color.WHITE);

        jMenuBar1.setBackground(Color.DARK_GRAY);
        jMenuBar1.setForeground(Color.WHITE);
        startDate.setText("Start Date");
        startDate.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
        endDate.setText("End Date");
        endDate.setFont(new Font("Roboto Mono", Font.PLAIN, 24));


        jMenuItem2.setText("Status");
        jMenuItem2.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
        jMenuItem2.addActionListener(actionEvent -> {
            handleStatus(actionEvent);
        });

        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Logout");
        jMenu6.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
        jMenu6.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                handleLogout(mouseEvent);
            }
        });

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);
        jp1.add(b1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }

        });

        jp1.setBorder(BorderFactory.createCompoundBorder( new EtchedBorder(),new EmptyBorder(25,25,25,25)));
//        jp1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jPanel1Layout);
       /* jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            //.addGap(0, 471, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            //.addGap(0, 317, Short.MAX_VALUE)
        );
        */
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                //.addGap(20, 24, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
////                                .addGap(46, 46, 46)
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel4,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                )
//                                .addContainerGap(141, Short.MAX_VALUE)
                        )
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                                        .addContainerGap(167, Short.MAX_VALUE)
//                                        .addComponent(jLabel6,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                        //.addGap(131, 131, 131)
//                                        )
)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                //.addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
//                                        .addComponent(jLabel4, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                //.addGap(43, 43, 43)
                                                .addComponent(jLabel3,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                //.addGap(40,40,40)
                                                .addComponent(jLabel7,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

                                                .addComponent(jLabel5,0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        )

                                                )
//                                //.addGap(43, 43, 43)
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        )
//                                .addContainerGap(126, Short.MAX_VALUE))
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                .addGroup(jPanel1Layout.createSequentialGroup()
//                                        //.addGap(116, 116, 116)
//                                        .addComponent(jLabel6, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                        .addContainerGap(184, Short.MAX_VALUE))
                        )
        );





//        jp2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp2.setBorder(BorderFactory.createCompoundBorder(new EtchedBorder(),new EmptyBorder(50,50,50,50)));
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jPanel2Layout);

        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                //.addGap(18, 18, 18)
                                                .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                //.addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                //.addGap(20, 20, 20)
                                                                ))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(applyButton)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(applyButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


//        jPanel2Layout.setHorizontalGroup(
//                jPanel2Layout.createSequentialGroup()
//                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
//
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(startDate, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
////                                .addGap(30,30,30)
//                                .addComponent(startDateTextField,javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        )
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(endDate)
////                                .addGap(30,30,30)
//                                .addComponent(endDateTextField, GroupLayout.PREFERRED_SIZE, 800, GroupLayout.PREFERRED_SIZE)
//                        )
//                )
//
//
//        );
//        jPanel2Layout.setVerticalGroup(
//                jPanel2Layout.createSequentialGroup()
//                .addGroup(jPanel2Layout.createParallelGroup()
//                    .addComponent(startDate)
////                    .addGap(30,30,30)
//                    .addComponent(startDateTextField,javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
//                )
//                .addGroup(jPanel2Layout.createParallelGroup()
//                    .addComponent(endDate)
////                    .addGap(30,30,30)
//                    .addComponent(endDateTextField, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
//                )
//
//        );






        jp3.setBorder(BorderFactory.createCompoundBorder(new EtchedBorder(),new EmptyBorder(25,25,25,25)));
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(GroupLayout.Alignment.CENTER)
////                        .addGap(0, 471, Short.MAX_VALUE)
                        .addComponent(leaveStatusLabel, 0 , GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        //.addGap(30,30,30)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createSequentialGroup()
                        .addComponent(leaveStatusLabel,0 , GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        //.addGap(30,30,30)
        );

//        jp4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jp4);
//        jp4.setLayout(jPanel4Layout);
//        jPanel4Layout.setHorizontalGroup(
//                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        //.addGap(0, 471, Short.MAX_VALUE)
//        );
//        jPanel4Layout.setVerticalGroup(
//                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        //.addGap(0, 317, Short.MAX_VALUE)
//        );


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                                //.addGap(50,50,50)
                                        .addContainerGap()

                                        .addComponent(jp1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                //.addContainerGap()
                                .addComponent(jp2, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                //.addContainerGap()
                                .addComponent(jp3, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()
                        )

        );

        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jp1, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                              .addContainerGap()
                                .addComponent(jp2, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                              .addContainerGap()
                                .addComponent(jp3, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()
                        )
        );


        pack();
    }// </editor-fold>

    private void handleLogout(MouseEvent actionEvent) {
        System.out.println("handleLogout called");
        setVisible(false);
        try {
            new login(true, conn).setVisible(true);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e) {
            e.printStackTrace();
        }
    }

    private void handleStatus(ActionEvent actionEvent)
    {
        try
        {
            Statement st = conn.createStatement();
            String s = "select l.status from LeaveDetails l inner join Person p on l.l_id = p.lid where p.pid = "+id+";";

            ResultSet res = st.executeQuery(s);

//            res.next();

            leaveStatus.setFont(new Font("Roboto Mono", Font.PLAIN, 24));
            leaveStatusLabel.setFont(new Font("Roboto Mono", Font.PLAIN, 24));

            if (res.next()){
                leaveStatusLabel.setText("Your current leave status is: " + res.getString(1));
            } else {
                leaveStatusLabel.setText("You have not applied for any leave");

            }



            jp3.setVisible(true);
            jp1.setVisible(false);
            jp2.setVisible(false);
            jp4.setVisible(false);
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }

    private void applyButtonClicked(ActionEvent actionEvent) {


        try {
            Statement st = conn.createStatement();
            String s1="Select a.aid,a.balance from Person p inner join Attendance a on a.aid = p.aid where p.pid="+id+";";
            ResultSet res = st.executeQuery(s1);
            res.next();
            String att = res.getString(2);

            String startDate = startDateTextField.getText();
            System.out.println("Start date :" + startDate);

            String endDate = endDateTextField.getText();
            System.out.println("End date :" + endDate);
            float FloatAtt = Float.parseFloat(att);
            if(FloatAtt > 75.0)
            {
                System.out.println("Attendance is above criteria: "+att);

                String s2 = "insert into LeaveDetails (designation,startdate,endDate,status) values('S','"+startDate+"','"+endDate+"','P');";
                st.executeUpdate(s2);

                String s4 = "select l_id from LeaveDetails;";

                res = st.executeQuery(s4);
                res.last();

                System.out.println(res.getString(1));
                String s3 = "update Person set lid ="+ res.getString(1)+" where pid = "+id+";";

                st.executeUpdate(s3);
                JOptionPane.showMessageDialog(this,"You have successfully applied for leave");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Your attendance is below 75!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "There was some error!! Please try again at a later time.");
            e.printStackTrace();
        }

//        Statement st = null;
//        try {
//            st = conn.createStatement();
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }
//        ResultSet res = null;
//        try {
//            String s1="Select a.aid,a.balance from Person p inner join Attendance a where p.pid="+id+";";
//            res = st.executeQuery(s1);
//            res.next();
//            System.out.println(res.getString(1));
//        } catch (SQLException e) {
//            e.printStackTrace();
//        }

    }

    private void leaveApplyClicked(ActionEvent evt) {
        System.out.println("Apply clicked");
        jp2.setVisible(true);
        jp1.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
    }


    private void formWindowActivated(java.awt.event.WindowEvent evt)
    {
        initProfile();
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
    }

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt)
    {
     initProfile();
    }

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt)
    {
        jp1.setVisible(false);
        jp2.setVisible(true);

    }

    private void initProfile(){

        try{

            System.out.println("Profile clicked");

            Statement st = null;
            try {
                st = conn.createStatement();
            } catch (SQLException e) {
                e.printStackTrace();
            }

            String s = "Select l.login_id,s.Name,s.division,a.balance from Login l inner join Person p on l.login_id = p.pid inner join Student s on s.s_id = p.sid inner join Attendance a on a.aid = p.aid where l.login_id =" + id + ";";

            ResultSet res = st.executeQuery(s);

            res.next();


            jLabel2.setText("Rollno: " + res.getString(1));
            jLabel2.setFont(new Font("Roboto Mono", Font.PLAIN, 24));

            jLabel3.setText("Name: " + res.getString(2));
            jLabel3.setFont(new Font("Roboto Mono", Font.PLAIN, 24));

            jLabel5.setText("Attendance: "+ res.getString(4) + "%");
            jLabel5.setFont(new Font("Roboto Mono", Font.PLAIN, 24));

            jLabel7.setText("Class: "+ res.getString(3));
            jLabel7.setFont(new Font("Roboto Mono", Font.PLAIN, 24));

            jp1.setVisible(true);
            jp2.setVisible(false);
            jp3.setVisible(false);
            jp4.setVisible(false);
        }  catch (SQLException e) {
            e.printStackTrace();
        }



    }


    // End of variables declaration
}
